create table USERS (
    USER_ID varchar(10) primary key,
    PASS varchar(40) not null,
    MAIL varchar(100) not null,
    USER_NAME varchar(40) not null,
    DATEOFBIRTH date not null
);
insert into USERS (USER_ID, PASS, MAIL,USER_NAME, DATEOFBIRTH)
values ('minato', '1234', 'yusuke.minato@miyabilonk.jp','湊　雄輔', '2001-05-01');

create table TASKGROUP (
    TASKGROUP_ID integer primary key auto_increment,
    TASKGROUP_NAME varchar(50) not null
);
insert into TASKGROUP (TASKGROUP_NAME)
values ('メール');
insert into TASKGROUP(TAKGROUP_NAME)
values('パソコンスキル');
insert into TASKGROUP(TASKGROUP_NAME)
values('タイピング');
insert into TASKGROUP(TASKGROUP_NAME)
values('軽作業');
insert into TASKGROUP(TASKGROUP_NAME)
values('面接対策');
insert into TASKGROUP(TASKGROUP_NAME)
values('応募書類作成');

CREATE TABLE TASKS (
    TASK_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(10) NOT NULL,
    TASKGROUP_ID INTEGER NOT NULL,
    TASK_CONTENT VARCHAR(255) NOT NULL,
    REGISTER_DATE DATE NOT NULL,
    TENTATIVE_START_DATETIME DATETIME NOT NULL,
    TENTATIVE_END_DATETIME DATETIME NOT NULL,
    START_DATETIME DATETIME,
    END_DATETIME DATETIME,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_TASKGROUP_ID FOREIGN KEY (TASKGROUP_ID) REFERENCES TASKGROUP(TASKGROUP_ID)
);
INSERT INTO TASKS (USER_ID, TASKGROUP_ID, TASK_CONTENT, REGISTER_DATE, TENTATIVE_START_DATETIME, TENTATIVE_END_DATETIME)
VALUES ('minato', 1, '午前中分メール対応', '2024-05-31', '2024-06-02 09:00:00', '2024-06-02 09:15:00');


/data/workoptimizer